name: pipeline

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Formatting
        uses: mrkkrp/ormolu-action@v3

      - name: Lints
        run: curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .

  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    needs: checks
    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.10", "9.0"]
        cabal: ["latest"]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Freeze
        run: cabal freeze

      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build
        run: |
          cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
          cabal build all

      - name: Test
        run: |
          cabal test all
